### PR TITLE
Add all allure integrations

### PR DESCRIPTION
**Pull request by kenodegard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This adds all of the other Python test framework integrations supported by allure. See https://github.com/allure-framework/allure-python

@nsoranzo I'd be happy to add my name to the maintainers list if you want, just let me know

### CODE REVIEW

**Comment by kenodegard** [comment]
@conda-forge-admin, please rerender

**Comment by kenodegard** [comment]
ping @nsoranzo

**Comment by nsoranzo** [comment]
> @nsoranzo I'd be happy to add my name to the maintainers list if you want, just let me know

@kenodegard Sorry for the late reply. Sure, please add yourself to the maintainers list.

**Comment by nsoranzo** [comment]
Given that this would create a feedstock with a GitHub URL different from its name, I am wondering if the correct process here would be to create a PR to the [staged-recipes](https://github.com/conda-forge/staged-recipes) repository, and once merged, archive this repository.

**Comment by kenodegard** [comment]
I wondered about that too and I see now that's the recommended solution when a rename is desired: https://conda-forge.org/docs/orga/guidelines.html#renaming-packages

I'll get that going

**Comment by kenodegard** [comment]
https://github.com/conda-forge/staged-recipes/pull/23089

**Comment by nsoranzo** [comment]
Great, thanks for finding the guidelines. I suppose you also need a PR for https://github.com/conda-forge/feedstock-outputs .

Should we close this PR?

**Comment by kenodegard** [comment]
closing in favor of https://github.com/conda-forge/staged-recipes/pull/23089

**Pull request closed without merging**
